[platformio]
default_envs = release

[env]
platform = espressif32@^6.13.0
board = esp32-c6-devkitm-1      ; The ESP32-C6 Super Mini is not officially supported in PlatformIO,
                                ; but the ESP32-C6 DevKitM-1 is compatible and can be used as a target board.
framework = espidf
board_upload.flash_size = 2MB   ; The default flash size is 4MB, but the ESP32-C6 Super Mini has only 2MB of flash memory.
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct

[env:debug]
build_type = debug
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.debug.defaults"

[env:release]
build_type = release
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.release.defaults"