[platformio]
default_envs = esp32c6

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitm-1
framework = espidf
board_build.sdkconfig_defaults = sdkconfig.defaults
board_upload.flash_size = 2MB
build_flags =
	-DLOG_LOCAL_LEVEL=ESP_LOG_INFO